zsh: allow to eval zsh completion
iterative/shtab pull request #159
Opened 2024-01-31 09:43 UTC by bjoernricks

Allow to run `eval "$(my-prog --print-completion zsh)"` to enable completion in the current zsh environment.

This change is inspired by https://github.com/pypa/pip/pull/12173 and https://github.com/pallets/click/pull/2544.

2024-01-31 14:40 UTC, casperdcl requested changes
Thanks! Do you want to update the failing tests too?

2024-01-31 15:52 UTC, bjoernricks commented
> Thanks! Do you want to update the failing tests too?

Done. The tests run successful at my machine with Python 3.11 now.

2024-01-31 18:11 UTC, casperdcl commented on tests/test_shtab.py
> +            "compdef _shtab_shtab -N script.py",]
```suggestion
            "compdef _shtab_shtab -N script.py"]
```

2024-01-31 18:13 UTC, casperdcl approved these changes

2024-01-31 18:13 UTC, merged

2024-02-01 07:01 UTC, bjoernricks commented
@casperdcl would it be possible to include this change in a new release?

2024-02-20 01:56 UTC, casperdcl commented
/tag v1.7.0 3b3ed28