Determine whether to add a subparser to completion by its presences in `_get_subactions()`
iterative/shtab pull request #47
Opened 2021-08-23 05:42 UTC by jimporter

This is just a small change to the logic for when to generate completion for a subparser. The new logic is the same that `argparse` uses for showing a subparser in the list of options. This is particularly important for subparsers which pass `add_help=False` in order to provide their *own* help implementation. (This is something I do in one of my projects. See [here](https://github.com/jimporter/bfg9000/blob/8102fe1c96f86b3afc58bc73da1f449f934f6c1a/bfg9000/driver.py#L315-L318) and [here](https://github.com/jimporter/bfg9000/blob/8102fe1c96f86b3afc58bc73da1f449f934f6c1a/bfg9000/driver.py#L145-L146) for an example.)

Note: this is a breaking change, since now subparsers with no `help` kwarg will no longer have shell-completion generated for them. I think this is the correct behavior though, and fixing this is easy enough for users of shtab: just set `help` to something like `None` or `''` (or even better, add an actual help message!).

2021-08-23 15:31 UTC, jimporter commented
> what about using `help=argparse.SUPPRESS` instead?

Unfortunately, that results in `myprogram --help` printing "==SUPPRESS==" for the subcommand's help string. It seems the only way to hide the subcommand from the help listing is to omit the `help` argument when calling `add_parser`: https://github.com/python/cpython/blob/ac87b07a10e0ba2834e8de9cf0ea29a40fd882b1/Lib/argparse.py#L1166-L1170

As a further enhancement here, I notice that shtab uses `subparser.description` for the shell-completion help string. Since we can use the value of `_get_subactions()` to get the value of `help`, maybe it would be better to use that instead of the description (which might be too long to show anything useful in the shell).

Another thing I just noticed that I didn't account for is subcommand aliases. I'll write a test for this and fix the patch as needed...

2021-08-24 22:45 UTC, casperdcl requested changes
slight tweaks

2021-08-24 22:45 UTC, casperdcl commented on shtab/__init__.py
> +
```suggestion
```

2021-08-24 22:45 UTC, casperdcl commented on shtab/__init__.py
> +                        if choice in public_cmds:
```suggestion
                        public_cmds = get_public_subcommands(positional)
                        if choice in public_cmds:
```

2021-08-24 22:45 UTC, casperdcl commented on shtab/__init__.py
> +    # parsers.
```suggestion
```

2021-08-24 23:16 UTC, casperdcl approved these changes

2021-08-24 23:16 UTC, merged

2021-08-24 23:17 UTC, casperdcl commented
/tag 1e1d6ef v1.4.0

2021-08-24 23:19 UTC, casperdcl commented
/tag v1.4.0 1e1d6ef

2021-08-25 04:42 UTC, jimporter commented
Thanks for the quick review/merge!

2021-08-25 07:37 UTC, casperdcl commented
Thanks for the contribution!