Fix #92
iterative/shtab pull request #93
Opened 2022-08-28 02:17 UTC by Freed-Wu

2022-10-26 21:47 UTC, casperdcl requested changes
- Would prefer a pre-commit version.
- How does the pre-commit version work? Does it require an internet connection or is the dictionary/logic on the local machine?

2022-10-26 21:55 UTC, casperdcl requested changes
nice! Sorry for the delay.

2022-10-26 21:55 UTC, casperdcl commented on shtab/__init__.py
> +        raise NotImplementedError
```suggestion
    pass
```

2022-10-27 00:45 UTC, Freed-Wu commented on shtab/__init__.py
> +        raise NotImplementedError
Fixed.

2022-10-28 23:27 UTC, casperdcl requested changes
minor typo

2022-10-28 23:27 UTC, casperdcl commented on shtab/__init__.py
> +  local context state line curcontext="$curcontext" one_or_more='(-)*' reminder='(*)'
```suggestion
  local context state line curcontext="$curcontext" one_or_more='(-)*' remainder='(*)'
```

2022-10-28 23:27 UTC, casperdcl commented on shtab/__init__.py
> +  if ((${{{prefix}_options[(I)${{(q)one_or_more}}*]}} + ${{{prefix}_options[(I)${{(q)reminder}}*]}} == 0)); then  # noqa: E501
```suggestion
  if ((${{{prefix}_options[(I)${{(q)one_or_more}}*]}} + ${{{prefix}_options[(I)${{(q)remainder}}*]}} == 0)); then  # noqa: E501
```

2022-10-29 08:09 UTC, Freed-Wu commented on shtab/__init__.py
> +  local context state line curcontext="$curcontext" one_or_more='(-)*' reminder='(*)'
Fixed.

2022-10-29 08:10 UTC, Freed-Wu commented on shtab/__init__.py
> +  if ((${{{prefix}_options[(I)${{(q)one_or_more}}*]}} + ${{{prefix}_options[(I)${{(q)reminder}}*]}} == 0)); then  # noqa: E501
Fixed.

2022-10-29 14:53 UTC, casperdcl commented
@Freed-Wu Thanks! You wrote `fixes #91` in a commit message, just clarifying you meant `fixes #90`, right?

2022-11-15 14:53 UTC, Freed-Wu commented
> @Freed-Wu Thanks! You wrote `fixes #91` in a commit message, just clarifying you meant `fixes #90`, right?

It also fix #91, which path completion failed in zsh. Because they are simple, I put them in one PR. If you like, I can split them to many PRs.

2022-11-18 22:10 UTC, casperdcl approved these changes
lgtm

2022-11-18 22:11 UTC, merged

2022-11-18 22:12 UTC, casperdcl commented
/tag v1.5.8 6779de6